<?php

namespace App\Helpers\Interfaces;

interface UniversityEventTypes
{
    const UNIVERSITY_EVENT_TYPE_OPENDAY = 0; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE table
    const UNIVERSITY_EVENT_TYPE_WORKSHOP = 0; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE_event_types table
    const UNIVERSITY_EVENT_TYPE_COMPITITION = 0; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE_event_types table
    const UNIVERSITY_EVENT_TYPE_STUDENT_FOR_DAY = 0; //TODO: UPDATE THE ID FOR UNIVERSITY_EVENT_TYPE_event_types table

}
